from . import ptt_document_type
from . import ptt_vendor_document
from . import ptt_vendor_service_pricing
from . import ptt_vendor_rfq
from . import ptt_vendor_quote_history
from . import ptt_vendor_task
from . import res_partner
from . import ptt_project_vendor_assignment
from . import project_project
