{
    "name": "PTT Operational Dashboard",
    "version": "19.0.1.0.0",
    "summary": "Party Time Texas operational dashboard with KPIs and quick actions",
    "category": "Customizations",
    "author": "Party Time Texas",
    "license": "LGPL-3",
    "depends": [
        "base",
        "web",
        "crm",
        "sale",
        "sale_crm",
        "sale_project",
        "project",
        "account",
        "analytic",
        "purchase",
        "ptt_business_core",
    ],
    "data": [
        "security/ptt_security.xml",
        "security/ir.model.access.csv",
        "views/ptt_sales_rep_views.xml",
        "views/ptt_sales_commission_views.xml",
        "views/ptt_dashboard_views.xml",
        "views/ptt_dashboard_menu.xml",
        "data/default_home_action.xml",
    ],
    "assets": {
        "web.assets_backend": [
            "ptt_operational_dashboard/static/src/dashboard_statistics_service.js",
            "ptt_operational_dashboard/static/src/components/**/*.js",
            "ptt_operational_dashboard/static/src/components/**/*.xml",
            "ptt_operational_dashboard/static/src/dashboard_controller.js",
            "ptt_operational_dashboard/static/src/dashboard.scss",
        ],
    },
    "installable": True,
    "application": True,
    "auto_install": False,
}

